"""
    Polysafe - User testing.
    Description:    Constants.
    File name:      constants.py
    Author:         Charles De Lafontaine
    Last edition:   06/22/2021
"""

CONSTANTS_REP = "constants"
ACTIVE_REP = "active"

# for dev_powertool
DEV_POWERTOOL_REP = "dev_powertool"
DEV_CREDENTIALS_REP = "dev_credentials"
EMAIL_REP = "EMAIL"
PASSWORD_REP = "PASSWORD"

# for test_mainpage
TEST_MAINPAGE_REP = "test_mainpage"
CHECK_URLS_REP = "check_urls"
CHECK_LOGIN_CREDENTIALS_REP = "check_login_credentials"
SEND_FAKE_LOGIN_CREDENTIALS_REP = "send_fake_login_credentials"
CHECK_ERROR_GENERATION_REP = "check_error_generation"
POLYSAFE_MAINPAGE_URL_REP = "POLYSAFE_MAINPAGE_URL"
CONNECTION_TEXT_REP = "CONNECTION_TEXT"
LIMIT_OF_RETRIES_REP = "LIMIT_OF_RETRIES"
EXPECTED_CONNECTION_URL_REP = "EXPECTED_CONNECTION_URL"
EMAIL_ID_REP = "EMAIL_ID"
PASSWORD_ID_REP = "PASSWORD_ID"
CONNECTION_BTN_ID_REP = "CONNECTION_BTN_ID"
INVALID_EMAIL_REP = "INVALID_EMAIL_EXAMPLE"
INVALID_PASSWORD_REP = "INVALID_PASSWORD_EXAMPLE"
CLOSE_BUTTON_REP = "CLOSE_BUTTON_NAME"
FORGOT_BUTTON_LINK_REP = "FORGOT_BUTTON_LNK_NAME"
CREATE_ACCOUNT_LINK_REP = "CREATE_ACCOUNT_LNK_NAME"
ABOUT_LINK_REP = "ABOUT_LNK_NAME"
SUPPORT_LINK_REP = "SUPPORT_LNK_NAME"

# for test_creation
TEST_CREATION_REP = "test_creation"
POLYSAFE_CREATE_ACCOUNT_URL_REP = "POLYSAFE_CREATE_ACCOUNT_URL"
VALID_REGISTRATION_NUMBER_LIST_REP = "VALID_REGISTRATION_NUMBER_LIST"
INVALID_REGISTRATION_NUMBER_LIST_REP = "INVALID_REGISTRATION_NUMBER_LIST"
VALID_NAME_LIST_REP = "VALID_NAME_LIST"
INVALID_NAME_LIST_REP = "INVALID_NAME_LIST"
VALID_EMAIL_LIST_REP = "VALID_EMAIL_LIST"
INVALID_EMAIL_LIST_REP = "INVALID_EMAIL_LIST"
VALID_PASSWORD_LIST_REP = "VALID_PASSWORD_LIST"
INVALID_PASSWORD_LIST_REP = "INVALID_PASSWORD_LIST"
VALID_CELLPHONE_NUMBER_LIST_REP = "VALID_CELLPHONE_NUMBER_LIST"
INVALID_CELLPHONE_NUMBER_LIST_REP = "INVALID_CELLPHONE_NUMBER_LIST"
ACCOUNT_CREATION_CONTRACT_LNK_REP = "ACCOUNT_CREATION_CONTRACT_LNK"
CHART_OF_PAYMENT_LNK_REP = "CHART_OF_PAYMENT_LNK"
LEGAL_LNK_REP = "LEGAL_LNK"
