"""
    Polysafe - User testing.
    Description:    Constants.
    File name:      constants.py
    Author:         Charles De Lafontaine
    Last edition:   07/21/2021
"""

from selenium.webdriver.chrome.options import Options

# Switch between local or online testing
# Online: https://polysafe.polymtl.ca/
# Offline (e.g.): http://localhost/polysafe_code/erp
TESTING_URL_REP = "http://localhost/polysafe_code/erp"
ERROR_404 = "The requested URL was not found on this server."
MULTI_THREADING_OPTIONS = ['m', 'M']
QUEUED_OPTIONS = ['q', 'Q']
CONNECTION_TEST = 'CONNECTION'
CONNECTION_TEST_ID = 1
CREATION_TEST = 'CREATION'
CREATION_TEST_ID = 2
RESET_PASSWORD_TEST = 'RESET_PASSWORD'
RESET_PASSWORD_TEST_ID = 3
ACCOUNT_HOME_TEST = 'ACCOUNT_HOME'
ACCOUNT_HOME_TEST_ID = 4
TESTS = [CONNECTION_TEST, CREATION_TEST, RESET_PASSWORD_TEST, ACCOUNT_HOME_TEST]
TEST_QUIT_OPTIONS = ['quit', 'QUIT', 'q', 'Q']
OPTIONS = Options()
# Add/remove options for debug
# OPTIONS.add_argument("--headless")
# OPTIONS.add_argument("--no-sandbox")
# OPTIONS.add_argument("--disable-dev-shm-usage")

# overall constants
CONSTANTS_REP = "CONSTANTS"
ACTIVE_REP = "ACTIVE"
EMAIL_ID_REP = "EMAIL_ID"
PASSWORD_ID_REP = "PASSWORD_ID"
ERROR_CLASS_LABEL_REP = "ERROR_CLASS_LABEL"

# for dev_powertool
DEV_POWERTOOL_REP = "DEV_POWERTOOL"
DEV_CREDENTIALS_REP = "DEV_CREDENTIALS"
EMAIL_REP = "EMAIL"
PASSWORD_REP = "PASSWORD"

# for test_mainpage
TEST_MAINPAGE_REP = "TEST_MAINPAGE_INDEX"
CHECK_URLS_REP = "CHECK_URLS"
CHECK_LOGIN_CREDENTIALS_REP = "CHECK_LOGIN_CREDENTIALS"
SEND_FAKE_LOGIN_CREDENTIALS_REP = "SEND_FAKE_LOGIN_CREDENTIALS"
CHECK_ERROR_GENERATION_REP = "CHECK_ERROR_GENERATION"
POLYSAFE_MAINPAGE_URL_REP = "POLYSAFE_MAINPAGE_URL"
CONNECTION_TEXT_REP = "CONNECTION_TEXT"
LIMIT_OF_RETRIES_REP = "LIMIT_OF_RETRIES"
EXPECTED_CONNECTION_URL_REP = "EXPECTED_CONNECTION_URL"
CONNECTION_BTN_ID_REP = "CONNECTION_BTN_ID"
INVALID_EMAIL_REP = "INVALID_EMAIL_EXAMPLE"
INVALID_PASSWORD_REP = "INVALID_PASSWORD_EXAMPLE"
CLOSE_BUTTON_REP = "CLOSE_BUTTON_NAME"
FORGOT_BUTTON_LINK_REP = "FORGOT_BUTTON_LNK_NAME"
CREATE_ACCOUNT_LINK_REP = "CREATE_ACCOUNT_LNK_NAME"
ABOUT_LINK_REP = "ABOUT_LNK_NAME"
SUPPORT_LINK_REP = "SUPPORT_LNK_NAME"

# for test_creation
TEST_CREATION_REP = "TEST_ACCOUNT_CREATION"
POLYSAFE_CREATE_ACCOUNT_URL_REP = "POLYSAFE_CREATE_ACCOUNT_URL"
VALID_REGISTRATION_NUMBER_LIST_REP = "VALID_REGISTRATION_NUMBER_LIST"
INVALID_REGISTRATION_NUMBER_LIST_REP = "INVALID_REGISTRATION_NUMBER_LIST"
VALID_NAME_LIST_REP = "VALID_NAME_LIST"
INVALID_NAME_LIST_REP = "INVALID_NAME_LIST"
VALID_EMAIL_LIST_REP = "VALID_EMAIL_LIST"
INVALID_EMAIL_LIST_REP = "INVALID_EMAIL_LIST"
VALID_PASSWORD_LIST_REP = "VALID_PASSWORD_LIST"
INVALID_PASSWORD_LIST_REP = "INVALID_PASSWORD_LIST"
VALID_CELLPHONE_NUMBER_LIST_REP = "VALID_CELLPHONE_NUMBER_LIST"
INVALID_CELLPHONE_NUMBER_LIST_REP = "INVALID_CELLPHONE_NUMBER_LIST"
ACCOUNT_CREATION_CONTRACT_LNK_REP = "ACCOUNT_CREATION_CONTRACT_LNK"
CHART_OF_PAYMENT_LNK_REP = "CHART_OF_PAYMENT_LNK"
LEGAL_LNK_REP = "LEGAL_LNK"
USERNAME_ID_REP = "USERNAME_ID"
FIRST_NAME_ID_REP = "FIRST_NAME_ID"
LAST_NAME_ID_REP = "LAST_NAME_ID"
CONFIRM_PASSWORD_ID_REP = "CONFIRM_PASSWORD_ID"
CELLPHONE_NUMBER_ID_REP = "CELLPHONE_NUMBER_ID"
CHECKBOX_CONTRACT_ID_REP = "CHECKBOX_CONTRACT_ID"
CHECKBOX_CHART_OF_PAYMENT_ID_REP = "CHECKBOX_CHART_OF_PAYMENT_ID"
CHECKBOX_LEGAL_ID_REP = "CHECKBOX_LEGAL_ID"
CREATE_ACCOUNT_BTN_LABEL_REP = "CREATE_ACCOUNT_BTN_LABEL"

# for test_reset_password
TEST_RESET_PASSWORD_REP = "TEST_RESET_PASSWORD"
EMAIL_QRY_CLASS_NAME_REP = "EMAIL_QRY_CLASS_NAME"
POLYSAFE_FORGOT_PASSWORD_URL_REP = "POLYSAFE_FORGOT_PASSWORD_URL"
RESET_BTN_CLASS_NAME_REP = "RESET_BTN_CLASS_NAME"

# for test_account_home
TEST_ACCOUNT_HOME_REP = "TEST_ACCOUNT_HOME_PAGE"
POLYSAFE_LOGIN_URL_REP = "POLYSAFE_LOGIN_URL"
ACCOUNT_REGISTRAR_VERIFIED_REP = "ACCOUNT_REGISTRAR_VERIFIED"
FORMATION_BTN_LABEL_REP = "FORMATION_BTN_LABEL"
RESERVE_BTN_LABEL_REP = "RESERVE_BTN_LABEL"
CONTACT_BTN_LABEL_REP = "CONTACT_BTN_LABEL"
CALENDAR_LNK_LABEL_REP = "CALENDAR_BTN_LABEL"
MEMBERSHIP_DETAILS_BTN_LABEL_REP = "MEMBERSHIP_DETAILS_BTN_LABEL"
BILLING_DETAILS_BTN_LABEL_REP = "BILLING_DETAILS_BTN_LABEL"
PURCHASE_DETAILS_BTN_LABEL_REP = "PURCHASE_DETAILS_BTN_LABEL"
MY_CALENDAR_LNK_LABEL_REP = "MY_CALENDAR_LNK_LABEL"
NEW_RESERVATION_LNK_LABEL_REP = "NEW_RESERVATION_LNK_LABEL"
PRINTING_LNK_LABEL_REP = "PRINTING_LNK_LABEL"
LIVE_PRINTING_LNK_LABEL_REP = "LIVE_PRINTING_LNK_LABEL"
RESERVE_LNK_LABEL_REP = "RESERVE_LNK_LABEL"
GLOBAL_CALENDAR_REP = "GLOBAL_CALENDAR"

